<?php
/**
 * @ignore
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}

/**
 * Test class for dates.
 * Generated by PHPUnit on 2010-08-02 at 17:11:21.
 */
class gestion_fichierTest extends MockedListeOptions {
	/**
	 * @var gestion_fichier
	 */
	protected $object;
	/**
	 * @var relation_fichier_machine
	 */
	protected $object_relation_fichier_machine;
	/**
	 * @var copie_donnees
	 */
	protected $object_copie_donnees;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		ob_start ();
		
		$this->object = new gestion_fichier ( false, "TEST GESTION FICHIER" );
		$this->object->setListeOptions ( $this->getListeOption () );
		$this->object_relation_fichier_machine = $this->createMock ( 'relation_fichier_machine' );
		$this->object_copie_donnees = $this->createMock ( 'copie_donnees', array (), array () );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers gestion_fichier::transfert_standard
	 */
	public function testTransfert_standard() {
		$this->object_copie_donnees->expects ( $this->any () )
			->method ( 'copie_donnees' )
			->will ( $this->returnValue ( array (
				"telecharger" => true 
		) ) );
		$this->object->setCopieDonnees ( $this->object_copie_donnees );
		
		$this->object_relation_fichier_machine->expects ( $this->at ( 0 ) )
			->method ( 'renvoi_structure_fichier' )
			->will ( $this->returnValue ( array (
				"TEST" 
		) ) );
		$this->object_relation_fichier_machine->expects ( $this->at ( 1 ) )
			->method ( 'modifie_donnees_structure_fichier' )
			->will ( $this->returnValue ( true ) );
		$this->object_relation_fichier_machine->expects ( $this->at ( 2 ) )
			->method ( 'modifie_donnees_structure_fichier' )
			->will ( $this->returnValue ( true ) );
		
		$this->object->getListeOptions ()
			->expects ( $this->any () )
			->method ( 'setOption' )
			->will ( $this->returnValue ( true ) );
		$dom = $this->createMock ('DOMDocument');
		$this->object->getListeOptions ()
			->expects ( $this->any () )
			->method ( 'getDomDatas' )
			->will ( $this->returnValue ( $dom ) );
		
		$this->assertTrue ( $this->object->transfert_standard ( $this->object_relation_fichier_machine, "get", "20100820", "1code!!", "nomFicSource", "dossier_service", "13", "55", "33", "20100819", "nomFicForce", "nomMachineForce" ) );
		$this->assertTrue ( $this->object->transfert_standard ( $this->object_relation_fichier_machine, "get", "20100820", false, "nomFicSource", "dossier_service", "13", "55", "33", "20100819", "nomFicForce", "nomMachineForce" ) );
	}
}
?>