<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-26 at 11:31:40.
 */
class requeteMongoDBTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var requeteMongoDB
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new requeteMongoDB;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers requeteMongoDB::fabrique_select
     * @todo   Implement testFabrique_select().
     */
    public function testFabrique_select()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::fabrique_where
     * @todo   Implement testFabrique_where().
     */
    public function testFabrique_where()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::fabrique_insert
     * @todo   Implement testFabrique_insert().
     */
    public function testFabrique_insert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::fabrique_set
     * @todo   Implement testFabrique_set().
     */
    public function testFabrique_set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::prepare_valeur_update
     * @todo   Implement testPrepare_valeur_update().
     */
    public function testPrepare_valeur_update()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::fabrique_order
     * @todo   Implement testFabrique_order().
     */
    public function testFabrique_order()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::creer_or
     * @todo   Implement testCreer_or().
     */
    public function testCreer_or()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::creer_inc
     * @todo   Implement testCreer_inc().
     */
    public function testCreer_inc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::ajouter
     * @todo   Implement testAjouter().
     */
    public function testAjouter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::selectionner
     * @todo   Implement testSelectionner().
     */
    public function testSelectionner()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::selectionner_distinct
     * @todo   Implement testSelectionner_distinct().
     */
    public function testSelectionner_distinct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::supprimer
     * @todo   Implement testSupprimer().
     */
    public function testSupprimer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::updater
     * @todo   Implement testUpdater().
     */
    public function testUpdater()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::liste_db
     * @todo   Implement testListe_db().
     */
    public function testListe_db()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers requeteMongoDB::liste_table
     * @todo   Implement testListe_table().
     */
    public function testListe_table()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
