<?php
namespace Zorille\framework;
use \stdClass as stdClass;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class VirtualMachineCommunTest extends MockedListeOptions {
	/**
     * @var VirtualMachineCommun
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = $this->getMockForAbstractClass ( 'Zorille\framework\VirtualMachineCommun' );
		//$this->object = new VirtualMachineCommun ( false, "TESTS VirtualMachineCommun" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers Zorille\framework\VirtualMachineCommun::retrouve_valeur_MOR
	 */
	public function testretrouve_valeur_MOR_array() {
		$this->assertEquals ( "MOID", $this->object->retrouve_valeur_MOR ( array (
				"_" => "MOID" 
		) ) );
	}

	/**
	 * @covers Zorille\framework\VirtualMachineCommun::retrouve_valeur_MOR
	 */
	public function testretrouve_valeur_MOR_objet() {
		$MOID = new stdClass ();
		$MOID->_ = "MOID";
		$this->assertEquals ( "MOID", $this->object->retrouve_valeur_MOR ( $MOID ) );
	}
}
