<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class StorageIOAllocationInfoTest extends MockedListeOptions {
	/**
     * @var StorageIOAllocationInfo
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new StorageIOAllocationInfo ( false, "TESTS StorageIOAllocationInfo" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers StorageIOAllocationInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$shares = $this->createMock ( "SharesInfo" );
		$shares->expects ( $this->any () )
			->method ( 'renvoi_donnees_soap' )
			->will ( $this->returnValue ( array (
				"SharesInfo" 
		) ) );
		$this->object->setLimit ( 3 )
			->setReservation ( 2 )
			->setShares ( $shares );
		$this->assertEquals ( array (
				'shares' => array (
						'SharesInfo' 
				),
				'limit' => 3,
				'reservation' => 2 
		), $this->object->renvoi_donnees_soap () );
	}

	/**
	 * @covers StorageIOAllocationInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$object = new arrayObject ();
		$this->assertEquals ( $object, $this->object->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers StorageIOAllocationInfo::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$object = new arrayObject ();
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "StorageIOAllocationInfo" );
		$this->assertEquals ( $resultat, $this->object->renvoi_objet_soap ( true ) );
	}
}
