<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class VirtualDeviceConnectInfoTest extends MockedListeOptions {
	/**
     * @var VirtualDeviceConnectInfo
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new VirtualDeviceConnectInfo ( false, "TESTS VirtualDeviceConnectInfo" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers VirtualDeviceConnectInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$this->object->setAllowGuestControl ( TRUE )
			->setConnected ( TRUE )
			->setStartConnected ( TRUE )
			->setStatus ( "status" );
		$this->assertEquals ( array (
				'startConnected' => true,
				'allowGuestControl' => true,
				'connected' => true,
				'status' => 'status' 
		), $this->object->renvoi_donnees_soap () );
	}

	/**
	 * @covers VirtualDeviceConnectInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$object = new arrayObject ( array (
				'startConnected' => false,
				'allowGuestControl' => false,
				'connected' => false 
		) );
		$this->assertEquals ( $object, $this->object->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers VirtualDeviceConnectInfo::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$object = new arrayObject ( array (
				'startConnected' => false,
				'allowGuestControl' => false,
				'connected' => false 
		) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "VirtualDeviceConnectInfo" );
		$this->assertEquals ( $resultat, $this->object->renvoi_objet_soap ( true ) );
	}
}
