<?php
namespace Zorille\framework;
use \Exception as Exception;
use \ArrayObject as ArrayObject;
use \soapvar as soapvar;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class VirtualSCSIControllerTest extends MockedListeOptions {
	/**
     * @var VirtualSCSIController
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new VirtualSCSIController ( false, "TESTS VirtualSCSIController" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers Zorille\framework\VirtualSCSIController::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Exception() {
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS VirtualSCSIController) Il faut un busNumber' );
		$this->object ->renvoi_donnees_soap ();
	}

	/**
	 * @covers Zorille\framework\VirtualSCSIController::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Exception2() {
		$this->object ->setBusNumber ( 1 );
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS VirtualSCSIController) Il faut un sharedBus valide' );
		$this->object ->renvoi_donnees_soap ();
	}

	/**
	 * @covers Zorille\framework\VirtualSCSIController::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$this->object ->setBusNumber ( 1 ) 
			->setTypeScsi ( "VirtualBusLogicController" ) 
			->setHotAddRemove ( TRUE ) 
			->setScsiCtlrUnitNumber ( 3 ) 
			->setSharedBus ( "noSharing" );
		$this ->assertEquals ( array ( 
				'busNumber' => 1, 
				'hotAddRemove' => true, 
				'scsiCtlrUnitNumber' => 3, 
				'sharedBus' => 'noSharing' ), $this->object ->renvoi_donnees_soap () );
	}

	/**
	 * @covers Zorille\framework\VirtualSCSIController::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$this->object ->setBusNumber ( 1 ) 
			->setSharedBus ( "noSharing" );
		$object = new arrayObject ( array ( 
				'busNumber' => 1, 
				'sharedBus' => 'noSharing' ) );
		$this ->assertEquals ( $object, $this->object ->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers Zorille\framework\VirtualSCSIController::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$this->object ->setBusNumber ( 1 ) 
			->setSharedBus ( "noSharing" ) 
			->setTypeScsi ( "VirtualBusLogicController" );
		$object = new arrayObject ( array ( 
				'busNumber' => 1, 
				'sharedBus' => 'noSharing' ) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "VirtualBusLogicController" );
		$this ->assertEquals ( $resultat, $this->object ->renvoi_objet_soap ( true ) );
	}
}
