<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class VirtualDevicePciBusSlotInfoTest extends MockedListeOptions {
	/**
     * @var VirtualDevicePciBusSlotInfo
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new VirtualDevicePciBusSlotInfo ( false, "TESTS VirtualDevicePciBusSlotInfo" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers VirtualDevicePciBusSlotInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Exception() {
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS VirtualDevicePciBusSlotInfo) Il faut un pciSlotNumber' );
		$this->object ->renvoi_donnees_soap ();
	}

	/**
	 * @covers VirtualDevicePciBusSlotInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$this->object ->setPciSlotNumber ( 3 );
		$this ->assertEquals ( array ( 
				'pciSlotNumber' => 3 ), $this->object ->renvoi_donnees_soap () );
	}

	/**
	 * @covers VirtualDevicePciBusSlotInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$this->object ->setPciSlotNumber ( 3 );
		$object = new arrayObject ( array ( 
				'pciSlotNumber' => 3 ) );
		$this ->assertEquals ( $object, $this->object ->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers VirtualDevicePciBusSlotInfo::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$this->object ->setPciSlotNumber ( 3 );
		$object = new arrayObject ( array ( 
				'pciSlotNumber' => 3 ) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "VirtualDevicePciBusSlotInfo" );
		$this ->assertEquals ( $resultat, $this->object ->renvoi_objet_soap ( true ) );
	}
}
