<?php
$INCLUDE_SITESCOPE = true;
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}

require_once __DOCUMENT_ROOT__ . "/HP/sitescope/sitescope_template_datas.class.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-26 at 11:06:09.
 */
class sitescope_template_datasTest extends PHPUnit\Framework\TestCase {
	/**
     * @var sitescope_template_datas
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new sitescope_template_datas ( "TESTS sitescope_template_datas", false );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
     * @covers sitescope_template_datas::reset_datas
     */
	public function testReset_datas() {
		$this->object ->reset_datas ();
		$this ->assertEquals ( "", $this->object ->getOS () );
		$this ->assertEquals ( "", $this->object ->getCI () );
		$this ->assertEquals ( array (), $this->object ->getIPs () );
		$this ->assertEquals ( "", $this->object ->getSchedule () );
		$this ->assertEquals ( array (), $this->object ->getDisks () );
		$this ->assertEquals ( array (), $this->object ->getServices () );
		$this ->assertEquals ( "", $this->object ->getDNS () );
		$this ->assertEquals ( "", $this->object ->getFQDN () );
		$this ->assertEquals ( array (), $this->object ->getScripts () );
	}

	/**
	 * @covers sitescope_template_datas::prepare_OS_global
	 */
	public function testPrepare_OS_global_Exception() {
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS sitescope_template_datas) OS introuvable : TEST' );
		$this->object ->setOS ( "TEST" );
		$this ->assertEquals ( "", $this->object ->getOSGlobal () );
	}

	/**
     * @covers sitescope_template_datas::prepare_OS_global
     */
	public function testPrepare_OS_global() {
		$this->object ->setOS ( "" );
		$this ->assertSame ( $this->object, $this->object ->prepare_OS_global () );
		$this ->assertEquals ( "", $this->object ->getOSGlobal () );
		
		$this->object ->setOS ( "WINDOWS" );
		$this ->assertSame ( $this->object, $this->object ->prepare_OS_global () );
		$this ->assertEquals ( "WINDOWS", $this->object ->getOSGlobal () );
		
		$this->object ->setOS ( "LINUX" );
		$this ->assertSame ( $this->object, $this->object ->prepare_OS_global () );
		$this ->assertEquals ( "LINUX", $this->object ->getOSGlobal () );
		
		$this->object ->setOS ( "UNIX : UNIX" );
		$this ->assertSame ( $this->object, $this->object ->prepare_OS_global () );
		$this ->assertEquals ( "UNIX", $this->object ->getOSGlobal () );
	}
}
