<?php
namespace Zorille\framework;
use \ArrayObject as ArrayObject;
use \soapvar as soapvar;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class VirtualMachineConfigSpecTest extends MockedListeOptions {
	/**
     * @var VirtualMachineConfigSpec
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new VirtualMachineConfigSpec ( false, "TEST VirtualMachineConfigSpec" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers Zorille\framework\VirtualMachineConfigSpec::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Valide() {
		$VirtualMachineDefaultPowerOpInfo = "OBJET TODO";
		
		$this->object->setDeviceChange ( array (
				'VirtualDeviceConfigSpec' 
		) )
			->setMemoryMB ( 2048 )
			->setNpivWorldWideNameOp ( "npivWorldWideNameOp" )
			->setNumCoresPerSocket ( 3 )
			->setNumCPUs ( 6 )
			->setPowerOpInfo ( $VirtualMachineDefaultPowerOpInfo ) //VirtualMachineDefaultPowerOpInfo
			->setVAppConfigRemoved ( TRUE )
			->setVirtualICH7MPresent ( TRUE )
			->setVirtualSMCPresent ( TRUE )
			->setVmProfile ( array (
				'VirtualMachineProfileSpec' 
		) );
		$this->assertEquals ( array (
				'deviceChange' => array (
						'VirtualDeviceConfigSpec' 
				),
				'memoryMB' => 2048,
				'npivWorldWideNameOp' => 'npivWorldWideNameOp',
				'numCoresPerSocket' => 3,
				'numCPUs' => 6,
				'powerOpInfo' => 'OBJET TODO',
				'vAppConfigRemoved' => true,
				'virtualICH7MPresent' => true,
				'virtualSMCPresent' => true,
				'vmProfile' => array (
						'VirtualMachineProfileSpec' 
				) 
		), $this->object->renvoi_donnees_soap () );
	}

	/**
	 * @covers Zorille\framework\VirtualMachineConfigSpec::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$object = new arrayObject ( array (
				'memoryMB' => 2048,
				'numCPUs' => 1 
		) );
		$this->assertEquals ( $object, $this->object->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers Zorille\framework\VirtualMachineConfigSpec::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$object = new arrayObject ( array (
				'memoryMB' => 2048,
				'numCPUs' => 1 
		) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "VirtualMachineConfigSpec" );
		$this->assertEquals ( $resultat, $this->object->renvoi_objet_soap ( true ) );
	}
}
