<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-25 at 17:26:39.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class serveur_pipeTest extends MockedListeOptions {
	/**
     * @var serveur_pipe
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new serveur_pipe ( "/tmp/zpipe.pipe", 0600, false, "TESTS serveur_pipe" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
     * @covers serveur_pipe::close
     */
	public function testClose() {
		$this->assertTrue ( $this->object->close ( ) );
	}
}
