<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class VirtualDiskFlatVer2BackingInfoTest extends MockedListeOptions {
	/**
     * @var VirtualDiskFlatVer2BackingInfo
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new VirtualDiskFlatVer2BackingInfo ( false, "TESTS VirtualDiskFlatVer2BackingInfo" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers VirtualDiskFlatVer2BackingInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Exception() {
		$this->object ->setFileName ( "FILENAME" );
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS VirtualDiskFlatVer2BackingInfo) Il faut un diskMode' );
		$this->object ->renvoi_donnees_soap ();
	}

	/**
	 * @covers VirtualDiskFlatVer2BackingInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$parent = $this ->createMock ( "VirtualDiskFlatVer2BackingInfo" );
		$parent ->expects ( $this ->any () ) 
			->method ( 'renvoi_donnees_soap' ) 
			->will ( $this ->returnValue ( array ( 
				"VirtualDiskFlatVer2BackingInfo" ) ) );
		$this->object ->setFileName ( "FILENAME" ) 
			->setDiskMode ( "persistent" ) 
			->setChangeId ( "changeId" ) 
			->setContentId ( "contentId" ) 
			->setDeltaDiskFormat ( "redoLogFormat" ) 
			->setDigestEnabled ( TRUE ) 
			->setDeltaGrainSize ( 3 ) 
			->setEagerlyScrub ( TRUE ) 
			->setParent ( $parent ) 
			->setSplit ( TRUE ) 
			->setThinProvisioned ( TRUE ) 
			->setUuid ( "UUID" ) 
			->setWriteThrough ( TRUE );
		$this ->assertEquals ( 
				array ( 
							'fileName' => 'FILENAME', 
							'diskMode' => 'persistent', 
							'changeId' => 'changeId', 
							'contentId' => 'contentId', 
							'eagerlyScrub' => true, 
							'parent' => Array ( 
									'VirtualDiskFlatVer2BackingInfo' ), 
							'digestEnabled' => true, 
							'deltaGrainSize' => 3, 
							'deltaDiskFormat' => 'redoLogFormat', 
							'split' => true, 
							'thinProvisioned' => true, 
							'uuid' => 'UUID', 
							'writeThrough' => true ), 
					$this->object ->renvoi_donnees_soap () );
	}

	/**
	 * @covers VirtualDiskFlatVer2BackingInfo::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$this->object ->setFileName ( "FILENAME" ) 
			->setDiskMode ( "persistent" );
		$object = new arrayObject ( array ( 
				'fileName' => 'FILENAME', 
				'diskMode' => 'persistent' ) );
		$this ->assertEquals ( $object, $this->object ->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers VirtualDiskFlatVer2BackingInfo::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$this->object ->setFileName ( "FILENAME" ) 
			->setDiskMode ( "persistent" );
		$object = new arrayObject ( array ( 
				'fileName' => 'FILENAME', 
				'diskMode' => 'persistent' ) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "VirtualDiskFlatVer2BackingInfo" );
		$this ->assertEquals ( $resultat, $this->object ->renvoi_objet_soap ( true ) );
	}
}
