<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-26 at 10:24:49.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class groupe_forksTest extends MockedListeOptions {
	/**
     * @var groupe_forks
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new groupe_forks ( false, 'TESTS groupe_forks' );
		$this->object->setListeOptions($this->getListeOption());
	/********************************************/
		/* CLASS IMPOSSIBLE EN TESTS UNITAIRES      */
	/********************************************/
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers groupe_forks::renvoi_liste_erreur
	 */
	public function testprepare_signaux() {
		$this->assertEquals (array(),  $this->object->renvoi_liste_erreur () );
	}
}
