<?php
namespace Zorille\framework;
use \Exception as Exception;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-25 at 16:51:50.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
require_once "cacti_API_fonctions.php";
class cacti_removeDeviceTest extends MockedListeOptions {
	/**
     * @var cacti_removeDevice
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new cacti_removeDevice ( false, "TESTS cacti_removeDevice" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
     * @covers Zorille\framework\cacti_removeDevice::executeCacti_removeDevice
     */
	public function testExecuteCacti_removeDevice_exception1() {
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS cacti_removeDevice) Il faut une Ip.' );
		$this->object ->executeCacti_removeDevice ();
	}

	/**
     * @covers Zorille\framework\cacti_removeDevice::executeCacti_removeDevice
     */
	public function testExecuteCacti_removeDevice_exception2() {
		$this->object ->setIp ( "IP" );
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS cacti_removeDevice) Ce CI n\'existe pas en base.' );
		$this->object ->executeCacti_removeDevice ();
	}

	/**
     * @covers Zorille\framework\cacti_removeDevice::executeCacti_removeDevice
     */
	public function testExecuteCacti_removeDevice_exception3() {
		$this->object ->setIp ( "IP" );
		$this->object ->setIp ( 'Addresse1' );
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS cacti_removeDevice) Probleme de suppression du CI' );
		$GLOBALS ['global_error_message'] = true;
		$this->object ->executeCacti_removeDevice ();
	}

	/**
     * @covers Zorille\framework\cacti_removeDevice::executeCacti_removeDevice
     */
	public function testExecuteCacti_removeDevice_valide() {
		$this->object ->setIp ( "IP" );
		$this->object ->setIp ( 'Addresse1' );
		$GLOBALS ['global_error_message'] = false;
		$this ->assertTrue ( $this->object ->executeCacti_removeDevice () );
	}
}
