<?php
namespace Zorille\framework;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-25 at 17:02:19.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class copie_donneesTest extends MockedListeOptions {
	/**
     * @var copie_donnees
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new copie_donnees ( false, false, "TESTS copie_donnees" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}
	
	/**
     * @covers Zorille\framework\copie_donnees::renvoieTypeCopie
     * @todo   Implement testRenvoieTypeCopie().
     */
	public function testRenvoieTypeCopie() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}

	/**
     * @covers Zorille\framework\copie_donnees::copie_donnees
     * @todo   Implement testCopie_donnees().
     */
	public function testCopie_donnees() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}


	/**
     * @covers Zorille\framework\copie_donnees::getFonctionsStandards
     * @todo   Implement testGetFonctionsStandards().
     */
	public function testGetFonctionsStandards() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}

	/**
     * @covers Zorille\framework\copie_donnees::setFonctionsStandards
     * @todo   Implement testSetFonctionsStandards().
     */
	public function testSetFonctionsStandards() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete ( 'This test has not been implemented yet.' );
	}
}
