<?php
namespace Zorille\framework;
use \Exception as Exception;
use \ArrayObject as ArrayObject;
use \soapvar as soapvar;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class CustomizationSysprepTextTest extends MockedListeOptions {
	/**
     * @var CustomizationSysprepText
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new CustomizationSysprepText ( false, "TESTS CustomizationSysprepText" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers Zorille\framework\CustomizationSysprepText::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Exception() {
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS CustomizationSysprepText) Il faut une value' );
		$this->object ->renvoi_donnees_soap ();
	}

	/**
	 * @covers Zorille\framework\CustomizationSysprepText::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$this->object ->setValue ( "SysPrep" );
		$this ->assertEquals ( array ( 
				'value' => 'SysPrep' ), $this->object ->renvoi_donnees_soap () );
	}

	/**
	 * @covers Zorille\framework\CustomizationSysprepText::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$this->object ->setValue ( "SysPrep" );
		$object = new arrayObject ( array ( 
				'value' => 'SysPrep' ) );
		$this ->assertEquals ( $object, $this->object ->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers Zorille\framework\CustomizationSysprepText::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$this->object ->setValue ( "SysPrep" );
		$object = new arrayObject ( array ( 
				'value' => 'SysPrep' ) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "CustomizationSysprepText" );
		$this ->assertEquals ( $resultat, $this->object ->renvoi_objet_soap ( true ) );
	}
}
