<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-09-07 at 11:31:16.
 */
if (! defined ( '__DOCUMENT_ROOT__' )) {
	require_once $_SERVER ["PWD"] . '/prepare.php';
}
class CustomizationFixedNameTest extends MockedListeOptions {
	/**
     * @var CustomizationFixedName
     */
	protected $object;

	/**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
	protected function setUp() {
		ob_start ();
		$this->object = new CustomizationFixedName ( false, "TESTS CustomizationFixedName" );
	}

	/**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
	protected function tearDown() {
		ob_end_clean ();
	}

	/**
	 * @covers CustomizationFixedName::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_Exception() {
		$this ->expectException(Exception::class);
        $this->expectExceptionMessage( '(TESTS CustomizationFixedName) Il faut un name' );
		$this ->assertEquals ( "Never reached", $this->object ->renvoi_donnees_soap () );
	}

	/**
	 * @covers CustomizationFixedName::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap() {
		$this->object ->setName ( "NOM" );
		$this ->assertEquals ( array ( 
				'name' => 'NOM' ), $this->object ->renvoi_donnees_soap () );
	}

	/**
	 * @covers CustomizationFixedName::renvoi_donnees_soap
	 */
	public function testrenvoi_donnees_soap_renvoi_objet() {
		$this->object ->setName ( "NOM" );
		$object = new arrayObject ( array ( 
				'name' => 'NOM' ) );
		$this ->assertEquals ( $object, $this->object ->renvoi_donnees_soap ( true ) );
	}

	/**
	 * @covers CustomizationFixedName::renvoi_objet_soap
	 */
	public function testrenvoi_objet_soap_renvoi_objet() {
		$this->object ->setName ( "NOM" );
		$object = new arrayObject ( array ( 
				'name' => 'NOM' ) );
		$resultat = new soapvar ( $object, SOAP_ENC_OBJECT, "CustomizationFixedName" );
		$this ->assertEquals ( $resultat, $this->object ->renvoi_objet_soap ( true ) );
	}
}
